#Name of you workflow
name: My Test Workflow

#Define the trigger event (s)
on: [push]

#Jobs run in  parallal by default, each row steps in sequence
jobs: 

#Job to print something out
say-hello:
	runs-on: ubuntu-latest
	steps:
	  - run: echo "Hello, GitHub Actions!"