name: My Test Workflow

on: push

jobs:
  job_1:
    name: say hello
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello, GitHub Actions!

   job_2:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y build-essential python3