# Name of your workflow
name: My Test Workflow

# Define the trigger event (s)
on: [push]

# Jobs run in  parallal by default, each row steps in sequence
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -name: Say hello
       run: echo Hello, GitHub Actions!
  # jobs
  build-and-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y build-essential python3